### ISSUE TITLE
[node-env] body parser for text/plain

### ISSUE THREAD

**Issue by erwinvaneyk** [fission/environments#125]
The NodeJs Express framework attempts to parse the body of any incoming request to JSON. So in case of a missing or unsupported content-type such as text/plain, Express will not be able to convert the body to JSON. It seems to basically ignore body.

To reproduce, take any NodeJs Fission function that uses the body of the request, and force the content-type of the request to be text/plain: `curl -d 'Hello world!' -H 'Content-Type: text/plain' $FISSION_ROUTER/fission-function/<fn>`. The result is that the `request.body` is an empty object.

It seems that [modifying the express environment's bodyparser](https://stackoverflow.com/questions/12345166/how-to-force-parse-request-body-as-plain-text-instead-of-json-in-express) could resolve this (but I haven't looked into it)

**Comment by soharab-ic** [comment]
@erwinvaneyk Please try latest [NodeJS environments](https://github.com/orgs/fission/packages?tab=packages&q=node) based on Node-22.
