### ISSUE TITLE
Binary environment does not process large POST bodies

### ISSUE THREAD

**Issue by Twalord** [fission/environments#157]
**Fission/Kubernetes version**

<pre>
$ fission version
client:
  fission/core:
    BuildDate: "2021-06-21T10:38:48Z"
    GitCommit: d06ad04341377bec6b8c905a440956b7d659d8fb
    Version: 1.13.1
server:
  fission/core:
    BuildDate: "2021-06-21T09:13:11Z"
    GitCommit: 401cbd597b63f5646e3e4be7df38870fdd617485
    Version: 1.13.1

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T21:04:39Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.8", GitCommit:"5575935422cc1cf5169dfc8847cb587aa47bac5a", GitTreeState:"clean", BuildDate:"2021-06-16T12:53:07Z", GoVersion:"go1.15.13", Compiler:"gc", Platform:"linux/amd64"}
</pre>

**Kubernetes platform (e.g. Google Kubernetes Engine)**
OpenStack + Rancher

**Describe the bug**

Sending Post request to fission functions in a binary environment with bodies above a certain size causes no response to be returned.

**To Reproduce**

Follow the example guide for binary environments to deploy hello.sh https://github.com/fission/environments/tree/master/binary/examples
hello.sh:
```bash
#!/bin/sh

echo "Hello World!"
```
Steps:
```bash
fission env create --name binary-env --image fission/binary-env

fission function create --name hello --env binary-env --code hello.sh

fission route create --method GET --url /hello --function hello

curl http://$FISSION_ROUTER/hello
```
returns Hello World!

Now change the route to POST.
```bash
# Might need to run 'fission route list' to get the route name
fission route update --function hello --method POST --url /hello --name $ROUTE_NAME
```
Running
```bash
curl http://$FISSION_ROUTER/hello -XPOST
# or
curl http://$FISSION_ROUTER/hello -XPOST -d "Test"
```
both return Hello World!
So far everything works as expected.
The hello.sh script makes no use of the POST body so it should not matter what is sent.
However when running
```bash
curl http://$FISSION_ROUTER/hello --data-binary @PATH_TO_SOME_FILE
```
Where the file is above a certain size, curl will timeout and return: (52) Empty reply from server

I tested with a 49 KB file which works and a 72 KB file which does not work.

**Expected result**

I expect fission binary environment to process POST bodies up to at least 2 MB.

In the above described case it should return Hello World! for the 72 KB file.

**Actual result**
Curl times out and prints:
cur: (52) Empty reply from server

**Screenshots/Dump file**

<pre>
$ fission support dump

If needed I can attach this after removing sensitive information.
</pre>

**Additional context**

Checking function logs with 
```bash
fission function log --name hello
```
before and after invoking the function with a 72KB POST body shows new log entries so it reaches the function but somewhere on its way back the Hello World! response is lost.

**Comment by sanketsudake** [comment]
Hi @Twalord  We have done a couple of fixes and better error reporting with latest binary environment. 
Could you please try if you are able to reproduce issue with more logs ?
https://environments.fission.io/

**Comment by Twalord** [comment]
I updated my binary environment to the newest version using 
```bash
fission env update --name binary-env --image fission/binary-env:1.32.1
```
and reran the test. Now it works 👍 

Therefore, I will close this issue.
