### ISSUE TITLE
Java later versions support and images

### ISSUE THREAD

**Issue by vishal-biyani** [fission/environments#189]
Currently, the Java version tested and officially supported in Fission is Java8. It might be good to test and publish images for the latest versions of Java - 11, 12, 13, etc.

**Comment by bdruth** [comment]
Any updates on this?

**Comment by brewsoftware** [comment]
Just bumping this issue, I haven't had a lot of time to look into the PR. Last time I checked though it seemed to be working. Would love for someone to pick up the PR and double check that it's all working as expected.

**Comment by Fabrizzz** [comment]
I have updated the jvm-jersey environment to use latest standards:  Java 17 LTE, Jersey 3.1, Jetty 11, Jakarta 10, Maven 3.9.1 and also replaced @Context (now deprecated) with @Inject to adhere to the new Jakarta Context Dependency Injection 4.0 and JAX-RS 3.1 specifications.
It still has to be tested (but unit tests work locally).
If anyone is interested, here is the repo: [https://github.com/Fabrizzz/Fission-Jvm17-Jersey-Env](https://github.com/Fabrizzz/Fission-Jvm17-Jersey-Env)

**Comment by soharab-ic** [comment]
Please try latest [jvm enviornments](https://github.com/orgs/fission/packages?q=22&sort_by=downloads_asc&tab=packages&sort_by=downloads_asc&q=jvm) based on Java 22 release.
