### ISSUE TITLE
Handle duplicate dependencies gracefully in JVM environment

### ISSUE THREAD

**Issue by vishal-biyani** [fission/environments#191]
If a dependency that is added is a duplicate of existing in JVM dependency or has further transitive dependencies then the function invocation fails. If possible, this kinda of things should be handled gracefully. Related issue: https://github.com/fission/fission/issues/841

**Comment by soharab-ic** [comment]
Please try latest [jvm enviornments](https://github.com/orgs/fission/packages?q=22&sort_by=downloads_asc&tab=packages&sort_by=downloads_asc&q=jvm) based on Java 22 release version.
