### ISSUE TITLE
Health Check for JVM issues

### ISSUE THREAD

**Issue by vishal-biyani** [fission/environments#194]
Currently, the JVM environment health checks do not indicate the real health of JVM. We need to modify the health check so that actual issues such as `OutOfMemoryExceptions` etc. cause the health checks to fail and Kubernetes to restart the pods.

**Comment by soharab-ic** [comment]
Please try latest [jvm enviornments](https://github.com/orgs/fission/packages?q=22&sort_by=downloads_asc&tab=packages&sort_by=downloads_asc&q=jvm) based on Java 22 release.
