### ISSUE TITLE
Update nodejs environment vulnerable dependencies

### ISSUE THREAD

**Issue by life1347** [fission/environments#195]
The Issue to track fission/fission#1220 fission/fission#1221 . The dependencies (`request-promise-native`, `underscore`) mentioned in PRs above do not ship any new releases yet. So open this issue for future tracking.

**Comment by sanketsudake** [comment]
This is resolved now. We don't see any standing vulnerabilities on updated nodejs env images.

Latests enviroments can be seen at https://environments.fission.io/
