### ISSUE TITLE
binary-env and compiled binaries / example hello.go

### ISSUE THREAD

**Issue by Algorab** [fission/environments#207]
**Fission/Kubernetes version**

<pre>
$ fission --version
client:
  fission/core:
    BuildDate: "2021-11-23T09:29:28Z"
    GitCommit: 5349a591
    Version: v1.15.0
server:
  fission/core:
    BuildDate: "2021-11-23T09:29:28Z"
    GitCommit: 5349a591
    Version: v1.15.0

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T21:04:39Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.7-3+7700880a5c71e2", GitCommit:"7700880a5c71e25c44491ef5c7d7fb30527d8337", GitTreeState:"clean", BuildDate:"2021-11-17T22:02:47Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}

</pre>

**Kubernetes platform (microk8s)**

**Describe the bug**
I tried the binary-env hello.go example from [binary hello.go example](https://github.com/fission/environments/tree/master/binary/examples#hellogo).  As is it described there, before I created the binary environment with the comand ```fission env create --name binary-env --image fission/binary-env``` taken from [requirements binary hello.go example](https://github.com/fission/environments/tree/master/binary/examples#requirements). With this command automatically the image tagged with latest will then used.

When I test the function with ```fission fn test --name hello-go ``` you can find in the logs the message 
```
poolmgr-binary-env-default-25878-54f65bfbbb-q6nqk binary-env 2021/12/07 15:21:00 Starting binary function execution
poolmgr-binary-env-default-25878-54f65bfbbb-q6nqk binary-env 2021/12/07 15:21:00 stderr: /userfunc/user: line 1: ELF�: not found
poolmgr-binary-env-default-25878-54f65bfbbb-q6nqk binary-env /userfunc/user: line 2: syntax error: unexpected "("
poolmgr-binary-env-default-25878-54f65bfbbb-q6nqk binary-env 
poolmgr-binary-env-default-25878-54f65bfbbb-q6nqk binary-env 2021/12/07 15:21:00 Error: failed to wait for subprocess: exit status 2

```

The latest tagged binary-env image is 1.32.1. Then I test older versions of the binary-env images. What I found out is
the the version 1.11.2 is working as expected and the latest one and print out Hello World! and the env-variables. All versions later than 1.11.2 produce the error above.

**To Reproduce**

Follow the example linked above, try different binary-env versions.

**Expected result**
cli:
```
fission fn test --name hello-go
Hello World!
Environment: [REQUEST_METHOD=GET REQUEST_URI=/ CONTENT_LENGTH=0 HTTP_X-FISSION-FUNCTION-RESOURCEVERSION=29214 HTTP_CONNECTION=close HTTP_ACCEPT-ENCODING=gzip HTTP_X-FISSION-FULL-URL=/fission-function/hello-go HTTP_X-FISSION-FUNCTION-NAMESPACE=default HTTP_X-FORWARDED-FOR=127.0.0.1 HTTP_X-FORWARDED-HOST=127.0.0.1:38277 HTTP_TRACEPARENT=00-bf5756fbca878321c8cd8bd84797f8b1-d3e80979f713d847-01 HTTP_X-FISSION-FUNCTION-NAME=hello-go HTTP_X-FISSION-FUNCTION-UID=bb81ed9c-14b9-4990-a5ea-562e8d981ab6 HTTP_USER-AGENT=Go-http-client/1.1 HTTP_FORWARDED=host=127.0.0.1:38277;]%        
```

**Actual result**
logs:
``` 
poolmgr-binary-env-default-25878-54f65bfbbb-q6nqk binary-env 2021/12/07 15:21:00 Starting binary function execution
poolmgr-binary-env-default-25878-54f65bfbbb-q6nqk binary-env 2021/12/07 15:21:00 stderr: /userfunc/user: line 1: ELF�: not found
poolmgr-binary-env-default-25878-54f65bfbbb-q6nqk binary-env /userfunc/user: line 2: syntax error: unexpected "("
poolmgr-binary-env-default-25878-54f65bfbbb-q6nqk binary-env 
poolmgr-binary-env-default-25878-54f65bfbbb-q6nqk binary-env 2021/12/07 15:21:00 Error: failed to wait for subprocess: exit status 2

``` 
cli:
```
 fission fn test --name hello-go
Error: Error calling function hello-go: 500; Please try again or fix the error: failed to wait for subprocess: exit status 2
Error: Error getting function logs from controller: error getting logs from controller, status code: '500'. Try to get logs from log database.
Error querying logs: Internal error - 502 Bad Gateway
Options:
....
```

**Comment by sanketsudake** [comment]
Probable fix WIP https://github.com/fission/environments/pull/208

**Comment by soharab-ic** [comment]
@Algorab Please try out latest [binary environment](https://github.com/orgs/fission/packages?tab=packages&q=binary).
