### ISSUE TITLE
JVM-11 Environment mis configurations

### ISSUE THREAD

**Issue by brewsoftware** [fission/environments#269]
**Describe the bug**
When booting up there are several problems with the docker file build as per the master branch. The two main issues are
* server.portnumber parameter isn't being passed properly. This was copied from the non-jersey file so just needs to be fixed
* There's a missing dependency in the POM as this was removed from the more recent jdk-11

**To Reproduce**

Look at the deploy logs. Sorry but I've solved it now locally so can confirm that the dependency being added fixes the POD build.
 
Merge request with update is pending and I'll post it to this issue.

**Comment by brewsoftware** [comment]
Also still seeing the following on command execution dumped from the function pod with a timeout occuring on fission fn test

kubectl logs poolmgr-jvm-11-default-37479-749d4df79-5p5z5 -n fission-function fetcher



"level":"error","ts":"2022-09-07T05:30:19.875Z","logger":"fetcher","caller":"http/server.go:2084","msg":"error specializing pod","trace_id":"8afb4c4030223afa768c4aebff73a7aa","error":"error specializing function pod: Invalid argument - Unrecognized field \"FunctionMetadata\" (class io.fission.FunctionLoadRequest), not marked as ignorable (3 known properties: \"filepath\", \"functionName\", \"url\"])\n at [Source: (org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream); line: 1, column: 117] (through reference chain: io.fission.FunctionLoadRequest[\"FunctionMetadata\"])","errorVerbose":"Invalid argument - Unrecognized field \"FunctionMetadata\" (class io.fission.FunctionLoadRequest), not marked as ignorable (3 known properties: \"filepath\", \"functionName\", \"url\"])\n at [Source: (org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream); line: 1, column: 117] (through reference chain: io.fission.FunctionLoadRequest[\"FunctionMetadata\"])\nerror specializing function pod\ngithub.com/fission/fission/pkg/fetcher.(*Fetcher).SpecializePod\n\tpkg/fetcher/fetcher.go:754\ngithub.com/fission/fission/pkg/fetcher.(*Fetcher).SpecializeHandler\n\tpkg/fetcher/fetcher.go:243\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/Cellar/go/1.18.2/libexec/src/net/http/server.go:2084\nnet/http.(*ServeMux).ServeHTTP\n\t/usr/local/Cellar/go/1.18.2/libexec/src/net/http/server.go:2462\ngo.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*Handler).ServeHTTP\n\t/Users/sanket/go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.29.0/handler.go:189\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/Cellar/go/1.18.2/libexec/src/net/http/server.go:2916\nnet/http.(*conn).serve\n\t/usr/local/Cellar/go/1.18.2/libexec/src/net/http/server.go:1966\nruntime.goexit\n\t/usr/local/Cellar/go/1.18.2/libexec/src/runtime/asm_amd64.s:1571","stacktrace":"net/http.HandlerFunc.ServeHTTP\n\t/usr/local/Cellar/go/1.18.2/libexec/src/net/http/server.go:2084\nnet/http.(*ServeMux).ServeHTTP\n\t/usr/local/Cellar/go/1.18.2/libexec/src/net/http/server.go:2462\ngo.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*Handler).ServeHTTP\n\t/Users/sanket/go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.29.0/handler.go:189\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/Cellar/go/1.18.2/libexec/src/net/http/server.go:2916\nnet/http.(*conn).serve\n\t/usr/local/Cellar/go/1.18.2/libexec/src/net/http/server.go:1966"}

**Comment by brewsoftware** [comment]
Answering myself here but the above is due to the upgrade of Java 11 requiring a different annotation source. I've updated to pull request to include this fix and now another issue has come up 

```
INFO: Entrypoint ... my.class.Entrypoint
java.io.FileNotFoundException: /userfunc/deployarchive (Is a directory)
	at java.base/java.io.RandomAccessFile.open0(Native Method)
	at java.base/java.io.RandomAccessFile.open(Unknown Source)
```

This is coming out of the JVM container though not the fetcher so it may not be related to the environment container as per 

If anyone knows the above feel free to comment otherwise I will take a look in the next few days.

**Comment by brewsoftware** [comment]
Duplicate of https://github.com/fission/environments/issues/189

Please close out and I'll move the notes over to the pull request

**Comment by soharab-ic** [comment]
@brewsoftware Please try latest [jvm-22 environment.](https://github.com/fission/environments/pkgs/container/jvm-jersey-env-22)
