### ISSUE TITLE
Environments repo CI-CD

### ISSUE THREAD

**Issue by vishal-biyani** [fission/environments#65]
The currently merged CI-CD work in https://github.com/fission/environments/pull/22 needs a few more enhancements:

- [ ] Add missing environments to the workflow & Skaffold so that they are picked up
- [ ] Run integration test from Fission for a given environment.
- [ ] Create a release workflow for each environment - which can build and push images when a new PR is merged

**Comment by soharab-ic** [comment]
Relevant PRs are merged.
Hence, closing the issue.
