### ISSUE TITLE
JVM & Java Environment Re-Design and support for latest JDK

### ISSUE THREAD

**Issue by vishal-biyani** [fission/environments#88]
Many Fission users are using JVM/Java environment but the JDK/JRE version currently in use is quite old. There are other shortcomings also listed below which need a redesign of the JVM environment with the latest versions of JDK and other features. This issue is to list current limitations, future expectations, and to document future design before implementation.

Related Issues:

1. Currently, the Fission library is in snapshot repo and should be in release version for broader usage: https://github.com/fission/fission/issues/1579 

2. Health check for JVM specifically are not very useful as of now: https://github.com/fission/fission/issues/926 

3. Because of Spring and other dependencies, the JVM is a bit heavier than it should be: https://github.com/fission/fission/issues/832  

4. There were issues parsing XML: https://github.com/fission/fission/issues/1505 

5. An easier way to use Fission POM: https://github.com/fission/fission/issues/833 

Future environment expectation

1. Newer versions of JDK/JRE supported: https://github.com/fission/fission/issues/1485

**Comment by soharab-ic** [comment]
Please try latest [jvm enviornments](https://github.com/orgs/fission/packages?q=22&sort_by=downloads_asc&tab=packages&sort_by=downloads_asc&q=jvm) based on Java 22 release.
